name: Build and Test
on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.28.0
      
      - name: Install dependencies
        run: |
          pnpm i
      
      - name: Build project
        run: |
          pnpm build
